version: '3.8'

services:
  app:
    container_name: nest-http
    image: nest/nest-http:latest
    command: node index.js --redis_host=redis --allowed_origins=${ALLOWED_ORIGINS} --jwt_secret=${JWT_SECRET} --color --cluster
    environment:
      - TZ=Asia/Shanghai
      - NODE_ENV=production
    restart: 'on-failure'
    volumes:
      - ./data/nest:/root/.nest

    ports:
      - '3333:3333'
    depends_on:
      - nest-postgres
      - redis
    links:
      - nest-postgres
      - redis
    networks:
      - app-network

  nest-postgres:
    image: postgres:14
    container_name: nest-postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - nest-postgres:/var/lib/postgresql/data


  redis:
    image: redis
    container_name: redis

    ports:
      - '6560:6379'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  nest-postgres:
    name: nest-postgres-db
